name : run-python-file

on :
  schedule:
    - cron: '0 0 * * *' # “At   */60 */2 * * *every 60th minute past every 2nd hour.”
  workflow_dispatch:

permissions:
  id-token: write
  contents: read # default

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name : run gtu notification

        env:
          SMTP_RECEIVER_EMAIL : ${{secrets.SMTP_RECEIVER_EMAIL}}
          SMTP_SENDER_EMAIL: ${{secrets.SMTP_SENDER_EMAIL}}
          SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}

        run: python main.py
      
