name : run-python-file

on :
  schedule:
    - cron: '* * * * *' # “At every 60th minute past every 2nd hour.”

permissions:
  id-token: write
  contents: read # default

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name : run gtu notification

        env:
          NUMBER : ${{secrets.NUMBER}}
        run: python main.py
      