name : run-python-file

on :
  push:
    branches:
      - main
      - dev
  schedule:

    - cron: '0 */2 * * *' # “At   0 */2 * * * =======>>>>>>> At minute 0 past every 2nd hour..”
  workflow_dispatch:

permissions:
  id-token: write
  contents: read # default



jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: saving to txt
          path: save.txt
      
      - name : run gtu notification
        env:
          SMTP_RECEIVER_EMAIL : ${{secrets.SMTP_RECEIVER_EMAIL}}
          SMTP_SENDER_EMAIL: ${{secrets.SMTP_SENDER_EMAIL}}
          SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}
        run: python main.py
      
