name : run-python-file

on :
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name : run gtu notification
        env:
          NUMBER : ${{secrets.NUMBER}}
        run: python main.py